---
title: "Badanie przeżycia"
author: ""
date: "2025-04-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r install}
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")

# BiocManager::install("TCGAbiolinks", version = "3.16", force = TRUE)

# install.packages("stringi", dependencies = TRUE)

# BiocManager::install("TCGAutils")
```

```{r library}
library(TCGAutils) 
library(TCGAbiolinks)
library(BiocManager)
library(dplyr)
library(data.table)
```



```{r dane_subtypes, echo=FALSE}
subtypes <- TCGAquery_subtype("BRCA")
head(subtypes)
colnames(subtypes)


# clinical2 <- GDCquery_clinic(project = "TCGA-BRCA", type = "clinical")
# head(clinical)


metadata <- GDCquery_clinic(project = "TCGA-BRCA", type = "biospecimen")
colnames(metadata)

```


```{r clinical_data}

clinical <- fread("clinical.tsv")

colnames(clinical)


clinical[clinical == "'--"] <- NA

clinical_clean <- clinical %>% 
  select_if(~ mean(is.na(.)) < 0.9)

colnames(clinical_clean)

######################################################################################################################################################
```


